//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinavmvcproject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int ogid { get; set; }
        public string ogad { get; set; }
        public string ogsoyad { get; set; }
        public string ogbolum { get; set; }
        public string ogkredi { get; set; }
    }
}
